# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "/net/sj-itnas01b/vol/vol1/abg/home/home/users/holiu/Ethernet_Project/90/Feb9_re-genTse-OptimizedHW-in90_startWith-90fbTSE-SGDMA/TSE_SGDMA/NiosII_stratixII_2s60_RoHS_TSE_SGDMA.qpf"
project_close