# TCL File Generated by Component Editor 8.0sp1
# Tue May 26 14:52:04 EDT 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | adBUF "adBUF" v1.0
# | null 2009.05.26.14:52:04
# | 
# | 
# | H:/Project/Ethernet/adBUF.v
# | 
# |    ./adBUF.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module adBUF
# | 
set_module_property NAME adBUF
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property DISPLAY_NAME adBUF
set_module_property TOP_LEVEL_HDL_FILE adBUF.v
set_module_property TOP_LEVEL_HDL_MODULE adBUF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file adBUF.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter INITIAL int 0
set_parameter_property INITIAL DISPLAY_NAME INITIAL
set_parameter_property INITIAL UNITS None
set_parameter_property INITIAL AFFECTS_PORT_WIDTHS true
add_parameter BUFFER0 int 1
set_parameter_property BUFFER0 DISPLAY_NAME BUFFER0
set_parameter_property BUFFER0 UNITS None
set_parameter_property BUFFER0 AFFECTS_PORT_WIDTHS true
add_parameter BUFFER1 int 2
set_parameter_property BUFFER1 DISPLAY_NAME BUFFER1
set_parameter_property BUFFER1 UNITS None
set_parameter_property BUFFER1 AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 minimumUninterruptedRunLength 1
set_interface_property s1 bridgesToMaster ""
set_interface_property s1 isMemoryDevice false
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 addressSpan 4096
set_interface_property s1 timingUnits Cycles
set_interface_property s1 setupTime 0
set_interface_property s1 writeWaitTime 0
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 readLatency 1
set_interface_property s1 printableDevice false

set_interface_property s1 ASSOCIATED_CLOCK clock_sink

add_interface_port s1 waitreq waitrequest Output 1
add_interface_port s1 a2do readdata Output 32
add_interface_port s1 rd read Input 1
add_interface_port s1 addr address Input 12
add_interface_port s1 cs_n chipselect_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

add_interface_port clock_sink rst_n reset_n Input 1
add_interface_port clock_sink rdclk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_sink

add_interface_port conduit_end a2dc export Input 12
add_interface_port conduit_end adclk export Input 1
add_interface_port conduit_end wrclk export Input 1
# | 
# +-----------------------------------
