// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Jan 24 17:36:51 2012

cpu_jtag_debug_module_arbitrator cpu_jtag_debug_module_arbitrator_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.cpu_data_master_address_to_slave(cpu_data_master_address_to_slave_sig) ,	// input [30:0] cpu_data_master_address_to_slave_sig
	.cpu_data_master_byteenable(cpu_data_master_byteenable_sig) ,	// input [3:0] cpu_data_master_byteenable_sig
	.cpu_data_master_debugaccess(cpu_data_master_debugaccess_sig) ,	// input  cpu_data_master_debugaccess_sig
	.cpu_data_master_latency_counter(cpu_data_master_latency_counter_sig) ,	// input [1:0] cpu_data_master_latency_counter_sig
	.cpu_data_master_read(cpu_data_master_read_sig) ,	// input  cpu_data_master_read_sig
	.cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register(cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register_sig) ,	// input  cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register_sig
	.cpu_data_master_write(cpu_data_master_write_sig) ,	// input  cpu_data_master_write_sig
	.cpu_data_master_writedata(cpu_data_master_writedata_sig) ,	// input [31:0] cpu_data_master_writedata_sig
	.cpu_instruction_master_address_to_slave(cpu_instruction_master_address_to_slave_sig) ,	// input [30:0] cpu_instruction_master_address_to_slave_sig
	.cpu_instruction_master_latency_counter(cpu_instruction_master_latency_counter_sig) ,	// input [1:0] cpu_instruction_master_latency_counter_sig
	.cpu_instruction_master_read(cpu_instruction_master_read_sig) ,	// input  cpu_instruction_master_read_sig
	.cpu_jtag_debug_module_readdata(cpu_jtag_debug_module_readdata_sig) ,	// input [31:0] cpu_jtag_debug_module_readdata_sig
	.cpu_jtag_debug_module_resetrequest(cpu_jtag_debug_module_resetrequest_sig) ,	// input  cpu_jtag_debug_module_resetrequest_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.cpu_data_master_granted_cpu_jtag_debug_module(cpu_data_master_granted_cpu_jtag_debug_module_sig) ,	// output  cpu_data_master_granted_cpu_jtag_debug_module_sig
	.cpu_data_master_qualified_request_cpu_jtag_debug_module(cpu_data_master_qualified_request_cpu_jtag_debug_module_sig) ,	// output  cpu_data_master_qualified_request_cpu_jtag_debug_module_sig
	.cpu_data_master_read_data_valid_cpu_jtag_debug_module(cpu_data_master_read_data_valid_cpu_jtag_debug_module_sig) ,	// output  cpu_data_master_read_data_valid_cpu_jtag_debug_module_sig
	.cpu_data_master_requests_cpu_jtag_debug_module(cpu_data_master_requests_cpu_jtag_debug_module_sig) ,	// output  cpu_data_master_requests_cpu_jtag_debug_module_sig
	.cpu_instruction_master_granted_cpu_jtag_debug_module(cpu_instruction_master_granted_cpu_jtag_debug_module_sig) ,	// output  cpu_instruction_master_granted_cpu_jtag_debug_module_sig
	.cpu_instruction_master_qualified_request_cpu_jtag_debug_module(cpu_instruction_master_qualified_request_cpu_jtag_debug_module_sig) ,	// output  cpu_instruction_master_qualified_request_cpu_jtag_debug_module_sig
	.cpu_instruction_master_read_data_valid_cpu_jtag_debug_module(cpu_instruction_master_read_data_valid_cpu_jtag_debug_module_sig) ,	// output  cpu_instruction_master_read_data_valid_cpu_jtag_debug_module_sig
	.cpu_instruction_master_requests_cpu_jtag_debug_module(cpu_instruction_master_requests_cpu_jtag_debug_module_sig) ,	// output  cpu_instruction_master_requests_cpu_jtag_debug_module_sig
	.cpu_jtag_debug_module_address(cpu_jtag_debug_module_address_sig) ,	// output [8:0] cpu_jtag_debug_module_address_sig
	.cpu_jtag_debug_module_begintransfer(cpu_jtag_debug_module_begintransfer_sig) ,	// output  cpu_jtag_debug_module_begintransfer_sig
	.cpu_jtag_debug_module_byteenable(cpu_jtag_debug_module_byteenable_sig) ,	// output [3:0] cpu_jtag_debug_module_byteenable_sig
	.cpu_jtag_debug_module_chipselect(cpu_jtag_debug_module_chipselect_sig) ,	// output  cpu_jtag_debug_module_chipselect_sig
	.cpu_jtag_debug_module_debugaccess(cpu_jtag_debug_module_debugaccess_sig) ,	// output  cpu_jtag_debug_module_debugaccess_sig
	.cpu_jtag_debug_module_readdata_from_sa(cpu_jtag_debug_module_readdata_from_sa_sig) ,	// output [31:0] cpu_jtag_debug_module_readdata_from_sa_sig
	.cpu_jtag_debug_module_reset_n(cpu_jtag_debug_module_reset_n_sig) ,	// output  cpu_jtag_debug_module_reset_n_sig
	.cpu_jtag_debug_module_resetrequest_from_sa(cpu_jtag_debug_module_resetrequest_from_sa_sig) ,	// output  cpu_jtag_debug_module_resetrequest_from_sa_sig
	.cpu_jtag_debug_module_write(cpu_jtag_debug_module_write_sig) ,	// output  cpu_jtag_debug_module_write_sig
	.cpu_jtag_debug_module_writedata(cpu_jtag_debug_module_writedata_sig) ,	// output [31:0] cpu_jtag_debug_module_writedata_sig
	.d1_cpu_jtag_debug_module_end_xfer(d1_cpu_jtag_debug_module_end_xfer_sig) 	// output  d1_cpu_jtag_debug_module_end_xfer_sig
);

