// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Jan 24 17:36:51 2012

ext_flash ext_flash_inst
(
	.address(address_sig) ,	// input [24:0] address_sig
	.read_n(read_n_sig) ,	// input  read_n_sig
	.select_n(select_n_sig) ,	// input  select_n_sig
	.write_n(write_n_sig) ,	// input  write_n_sig
	.data(data_sig) 	// inout [15:0] data_sig
);

