// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Jan 24 17:36:51 2012

SS_OCT_SOPC_burst_0_upstream_arbitrator SS_OCT_SOPC_burst_0_upstream_arbitrator_inst
(
	.SS_OCT_SOPC_burst_0_upstream_readdata(SS_OCT_SOPC_burst_0_upstream_readdata_sig) ,	// input [255:0] SS_OCT_SOPC_burst_0_upstream_readdata_sig
	.SS_OCT_SOPC_burst_0_upstream_readdatavalid(SS_OCT_SOPC_burst_0_upstream_readdatavalid_sig) ,	// input  SS_OCT_SOPC_burst_0_upstream_readdatavalid_sig
	.SS_OCT_SOPC_burst_0_upstream_waitrequest(SS_OCT_SOPC_burst_0_upstream_waitrequest_sig) ,	// input  SS_OCT_SOPC_burst_0_upstream_waitrequest_sig
	.clk(clk_sig) ,	// input  clk_sig
	.clock_crossing_0_m1_address_to_slave(clock_crossing_0_m1_address_to_slave_sig) ,	// input [29:0] clock_crossing_0_m1_address_to_slave_sig
	.clock_crossing_0_m1_burstcount(clock_crossing_0_m1_burstcount_sig) ,	// input [3:0] clock_crossing_0_m1_burstcount_sig
	.clock_crossing_0_m1_byteenable(clock_crossing_0_m1_byteenable_sig) ,	// input [31:0] clock_crossing_0_m1_byteenable_sig
	.clock_crossing_0_m1_latency_counter(clock_crossing_0_m1_latency_counter_sig) ,	// input  clock_crossing_0_m1_latency_counter_sig
	.clock_crossing_0_m1_read(clock_crossing_0_m1_read_sig) ,	// input  clock_crossing_0_m1_read_sig
	.clock_crossing_0_m1_write(clock_crossing_0_m1_write_sig) ,	// input  clock_crossing_0_m1_write_sig
	.clock_crossing_0_m1_writedata(clock_crossing_0_m1_writedata_sig) ,	// input [255:0] clock_crossing_0_m1_writedata_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.SS_OCT_SOPC_burst_0_upstream_address(SS_OCT_SOPC_burst_0_upstream_address_sig) ,	// output [29:0] SS_OCT_SOPC_burst_0_upstream_address_sig
	.SS_OCT_SOPC_burst_0_upstream_burstcount(SS_OCT_SOPC_burst_0_upstream_burstcount_sig) ,	// output [3:0] SS_OCT_SOPC_burst_0_upstream_burstcount_sig
	.SS_OCT_SOPC_burst_0_upstream_byteaddress(SS_OCT_SOPC_burst_0_upstream_byteaddress_sig) ,	// output [34:0] SS_OCT_SOPC_burst_0_upstream_byteaddress_sig
	.SS_OCT_SOPC_burst_0_upstream_byteenable(SS_OCT_SOPC_burst_0_upstream_byteenable_sig) ,	// output [31:0] SS_OCT_SOPC_burst_0_upstream_byteenable_sig
	.SS_OCT_SOPC_burst_0_upstream_debugaccess(SS_OCT_SOPC_burst_0_upstream_debugaccess_sig) ,	// output  SS_OCT_SOPC_burst_0_upstream_debugaccess_sig
	.SS_OCT_SOPC_burst_0_upstream_read(SS_OCT_SOPC_burst_0_upstream_read_sig) ,	// output  SS_OCT_SOPC_burst_0_upstream_read_sig
	.SS_OCT_SOPC_burst_0_upstream_readdata_from_sa(SS_OCT_SOPC_burst_0_upstream_readdata_from_sa_sig) ,	// output [255:0] SS_OCT_SOPC_burst_0_upstream_readdata_from_sa_sig
	.SS_OCT_SOPC_burst_0_upstream_waitrequest_from_sa(SS_OCT_SOPC_burst_0_upstream_waitrequest_from_sa_sig) ,	// output  SS_OCT_SOPC_burst_0_upstream_waitrequest_from_sa_sig
	.SS_OCT_SOPC_burst_0_upstream_write(SS_OCT_SOPC_burst_0_upstream_write_sig) ,	// output  SS_OCT_SOPC_burst_0_upstream_write_sig
	.SS_OCT_SOPC_burst_0_upstream_writedata(SS_OCT_SOPC_burst_0_upstream_writedata_sig) ,	// output [255:0] SS_OCT_SOPC_burst_0_upstream_writedata_sig
	.clock_crossing_0_m1_granted_SS_OCT_SOPC_burst_0_upstream(clock_crossing_0_m1_granted_SS_OCT_SOPC_burst_0_upstream_sig) ,	// output  clock_crossing_0_m1_granted_SS_OCT_SOPC_burst_0_upstream_sig
	.clock_crossing_0_m1_qualified_request_SS_OCT_SOPC_burst_0_upstream(clock_crossing_0_m1_qualified_request_SS_OCT_SOPC_burst_0_upstream_sig) ,	// output  clock_crossing_0_m1_qualified_request_SS_OCT_SOPC_burst_0_upstream_sig
	.clock_crossing_0_m1_read_data_valid_SS_OCT_SOPC_burst_0_upstream(clock_crossing_0_m1_read_data_valid_SS_OCT_SOPC_burst_0_upstream_sig) ,	// output  clock_crossing_0_m1_read_data_valid_SS_OCT_SOPC_burst_0_upstream_sig
	.clock_crossing_0_m1_read_data_valid_SS_OCT_SOPC_burst_0_upstream_shift_register(clock_crossing_0_m1_read_data_valid_SS_OCT_SOPC_burst_0_upstream_shift_register_sig) ,	// output  clock_crossing_0_m1_read_data_valid_SS_OCT_SOPC_burst_0_upstream_shift_register_sig
	.clock_crossing_0_m1_requests_SS_OCT_SOPC_burst_0_upstream(clock_crossing_0_m1_requests_SS_OCT_SOPC_burst_0_upstream_sig) ,	// output  clock_crossing_0_m1_requests_SS_OCT_SOPC_burst_0_upstream_sig
	.d1_SS_OCT_SOPC_burst_0_upstream_end_xfer(d1_SS_OCT_SOPC_burst_0_upstream_end_xfer_sig) 	// output  d1_SS_OCT_SOPC_burst_0_upstream_end_xfer_sig
);

