// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Jan 24 17:36:51 2012

tse_mac_control_port_arbitrator tse_mac_control_port_arbitrator_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.cpu_data_master_address_to_slave(cpu_data_master_address_to_slave_sig) ,	// input [30:0] cpu_data_master_address_to_slave_sig
	.cpu_data_master_latency_counter(cpu_data_master_latency_counter_sig) ,	// input [1:0] cpu_data_master_latency_counter_sig
	.cpu_data_master_read(cpu_data_master_read_sig) ,	// input  cpu_data_master_read_sig
	.cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register(cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register_sig) ,	// input  cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register_sig
	.cpu_data_master_write(cpu_data_master_write_sig) ,	// input  cpu_data_master_write_sig
	.cpu_data_master_writedata(cpu_data_master_writedata_sig) ,	// input [31:0] cpu_data_master_writedata_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.tse_mac_control_port_readdata(tse_mac_control_port_readdata_sig) ,	// input [31:0] tse_mac_control_port_readdata_sig
	.tse_mac_control_port_waitrequest(tse_mac_control_port_waitrequest_sig) ,	// input  tse_mac_control_port_waitrequest_sig
	.cpu_data_master_granted_tse_mac_control_port(cpu_data_master_granted_tse_mac_control_port_sig) ,	// output  cpu_data_master_granted_tse_mac_control_port_sig
	.cpu_data_master_qualified_request_tse_mac_control_port(cpu_data_master_qualified_request_tse_mac_control_port_sig) ,	// output  cpu_data_master_qualified_request_tse_mac_control_port_sig
	.cpu_data_master_read_data_valid_tse_mac_control_port(cpu_data_master_read_data_valid_tse_mac_control_port_sig) ,	// output  cpu_data_master_read_data_valid_tse_mac_control_port_sig
	.cpu_data_master_requests_tse_mac_control_port(cpu_data_master_requests_tse_mac_control_port_sig) ,	// output  cpu_data_master_requests_tse_mac_control_port_sig
	.d1_tse_mac_control_port_end_xfer(d1_tse_mac_control_port_end_xfer_sig) ,	// output  d1_tse_mac_control_port_end_xfer_sig
	.tse_mac_control_port_address(tse_mac_control_port_address_sig) ,	// output [7:0] tse_mac_control_port_address_sig
	.tse_mac_control_port_read(tse_mac_control_port_read_sig) ,	// output  tse_mac_control_port_read_sig
	.tse_mac_control_port_readdata_from_sa(tse_mac_control_port_readdata_from_sa_sig) ,	// output [31:0] tse_mac_control_port_readdata_from_sa_sig
	.tse_mac_control_port_reset(tse_mac_control_port_reset_sig) ,	// output  tse_mac_control_port_reset_sig
	.tse_mac_control_port_waitrequest_from_sa(tse_mac_control_port_waitrequest_from_sa_sig) ,	// output  tse_mac_control_port_waitrequest_from_sa_sig
	.tse_mac_control_port_write(tse_mac_control_port_write_sig) ,	// output  tse_mac_control_port_write_sig
	.tse_mac_control_port_writedata(tse_mac_control_port_writedata_sig) 	// output [31:0] tse_mac_control_port_writedata_sig
);

