// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Jan 24 17:36:51 2012

vol_transfer_done_pio_s1_arbitrator vol_transfer_done_pio_s1_arbitrator_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.peripheral_clock_crossing_m1_address_to_slave(peripheral_clock_crossing_m1_address_to_slave_sig) ,	// input [9:0] peripheral_clock_crossing_m1_address_to_slave_sig
	.peripheral_clock_crossing_m1_latency_counter(peripheral_clock_crossing_m1_latency_counter_sig) ,	// input  peripheral_clock_crossing_m1_latency_counter_sig
	.peripheral_clock_crossing_m1_nativeaddress(peripheral_clock_crossing_m1_nativeaddress_sig) ,	// input [7:0] peripheral_clock_crossing_m1_nativeaddress_sig
	.peripheral_clock_crossing_m1_read(peripheral_clock_crossing_m1_read_sig) ,	// input  peripheral_clock_crossing_m1_read_sig
	.peripheral_clock_crossing_m1_write(peripheral_clock_crossing_m1_write_sig) ,	// input  peripheral_clock_crossing_m1_write_sig
	.peripheral_clock_crossing_m1_writedata(peripheral_clock_crossing_m1_writedata_sig) ,	// input [31:0] peripheral_clock_crossing_m1_writedata_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.vol_transfer_done_pio_s1_readdata(vol_transfer_done_pio_s1_readdata_sig) ,	// input  vol_transfer_done_pio_s1_readdata_sig
	.d1_vol_transfer_done_pio_s1_end_xfer(d1_vol_transfer_done_pio_s1_end_xfer_sig) ,	// output  d1_vol_transfer_done_pio_s1_end_xfer_sig
	.peripheral_clock_crossing_m1_granted_vol_transfer_done_pio_s1(peripheral_clock_crossing_m1_granted_vol_transfer_done_pio_s1_sig) ,	// output  peripheral_clock_crossing_m1_granted_vol_transfer_done_pio_s1_sig
	.peripheral_clock_crossing_m1_qualified_request_vol_transfer_done_pio_s1(peripheral_clock_crossing_m1_qualified_request_vol_transfer_done_pio_s1_sig) ,	// output  peripheral_clock_crossing_m1_qualified_request_vol_transfer_done_pio_s1_sig
	.peripheral_clock_crossing_m1_read_data_valid_vol_transfer_done_pio_s1(peripheral_clock_crossing_m1_read_data_valid_vol_transfer_done_pio_s1_sig) ,	// output  peripheral_clock_crossing_m1_read_data_valid_vol_transfer_done_pio_s1_sig
	.peripheral_clock_crossing_m1_requests_vol_transfer_done_pio_s1(peripheral_clock_crossing_m1_requests_vol_transfer_done_pio_s1_sig) ,	// output  peripheral_clock_crossing_m1_requests_vol_transfer_done_pio_s1_sig
	.vol_transfer_done_pio_s1_address(vol_transfer_done_pio_s1_address_sig) ,	// output [1:0] vol_transfer_done_pio_s1_address_sig
	.vol_transfer_done_pio_s1_chipselect(vol_transfer_done_pio_s1_chipselect_sig) ,	// output  vol_transfer_done_pio_s1_chipselect_sig
	.vol_transfer_done_pio_s1_readdata_from_sa(vol_transfer_done_pio_s1_readdata_from_sa_sig) ,	// output  vol_transfer_done_pio_s1_readdata_from_sa_sig
	.vol_transfer_done_pio_s1_reset_n(vol_transfer_done_pio_s1_reset_n_sig) ,	// output  vol_transfer_done_pio_s1_reset_n_sig
	.vol_transfer_done_pio_s1_write_n(vol_transfer_done_pio_s1_write_n_sig) ,	// output  vol_transfer_done_pio_s1_write_n_sig
	.vol_transfer_done_pio_s1_writedata(vol_transfer_done_pio_s1_writedata_sig) 	// output  vol_transfer_done_pio_s1_writedata_sig
);

