obj/iniche/ins_tse_mac.o:  \
 /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/UCOSII/src/iniche/ins_tse_mac.c \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdlib.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/newlib.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/config.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/ieeefp.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stddef.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/reent.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/_ansi.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/_types.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/stdlib.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/alloca.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/stdio.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/include/stdarg.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/types.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/machine/types.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/stdio.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/string.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/unistd.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/unistd.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/features.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/io.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/UCOSII/inc/os_cpu.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/errno.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/errno.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/priv/alt_legacy_irq.h \
  system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/nios2.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  system_description/ipport.h system_description/system.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/nptypes.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/UCOSII/inc/includes.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/UCOSII/inc/os_cpu.h \
  /cygdrive/c/altera/91/nios2eds/components/micrium_uc_osii/UCOSII/inc/os_cfg.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_alarm.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/priv/alt_alarm.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h \
  /cygdrive/c/altera/91/nios2eds/components/micrium_uc_osii/UCOSII/inc/ucos_ii.h \
  /cygdrive/c/altera/91/nios2eds/components/micrium_uc_osii/UCOSII/inc/os_cfg.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/tk_crnos.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/libport.h \
  /cygdrive/c/altera/91/nios2eds/bin/nios2-gnutools/H-i686-pc-cygwin/bin/../lib/gcc/nios2-elf/3.4.6/../../../../nios2-elf/include/sys/time.h \
  /cygdrive/c/altera/91/nios2eds/components/micrium_uc_osii/UCOSII/inc/ucos_ii.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/in_utils.h \
  system_description/ipport.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/libport.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/netbuf.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/net.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/q.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/profiler.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/q.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/ether.h \
  system_description/system.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_timer/inc/altera_avalon_timer_regs.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sgdma/HAL/inc/altera_avalon_sgdma_descriptor.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/HAL/inc/altera_avalon_tse.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/inc/triple_speed_ethernet_regs.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/alt_types.h \
  system_description/system.h system_description/ipport.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sgdma/HAL/inc/altera_avalon_sgdma.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_dev.h \
  system_description/system.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/priv/alt_dev_llist.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sgdma/HAL/inc/altera_avalon_sgdma_descriptor.h \
  /cygdrive/c/altera/91/ip/altera/nios2_ip/altera_nios2/HAL/inc/sys/alt_irq.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_cache.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/inc/triple_speed_ethernet_regs.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/UCOSII/inc/iniche/triple_speed_ethernet_iniche.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/inc/alt_iniche_dev.h \
  system_description/ipport.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/tcpport.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/netbuf.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/net.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/ip.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/nptcp.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/mbuf.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/socket.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/sockvar.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/sockcall.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/bsdsock.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/tcpport.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_hal/HAL/inc/sys/alt_llist.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/inc/triple_speed_ethernet_regs.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/UCOSII/inc/iniche/ins_tse_mac.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sgdma/inc/altera_avalon_sgdma_regs.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sgdma/HAL/inc/altera_avalon_sgdma.h \
  /cygdrive/c/altera/91/ip/altera/sopc_builder_ip/altera_avalon_sgdma/HAL/inc/altera_avalon_sgdma_descriptor.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/HAL/inc/altera_avalon_tse.h \
  system_description/ipport.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/tcpport.h \
  /cygdrive/c/altera/91/ip/altera/triple_speed_ethernet/lib/sopc_builder/altera_triple_speed_ethernet/UCOSII/inc/iniche/ins_tse_mac.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/socket.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/src/h/tcpapp.h \
  /cygdrive/c/altera/91/nios2eds/components/altera_iniche/UCOSII/inc/alt_iniche_dev.h
