// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Wed Sep 14 13:52:08 2011

sample_addressing_custom sample_addressing_custom_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.sclr(sclr_sig) ,	// input  sclr_sig
	.sample_position(sample_position_sig) ,	// output [10:0] sample_position_sig
	.acq_busy(acq_busy_sig) ,	// output  acq_busy_sig
	.acq_done(acq_done_sig) ,	// output  acq_done_sig
	.dualMSB_write(dualMSB_write_sig) ,	// output  dualMSB_write_sig
	.dualMSB_read(dualMSB_read_sig) 	// output  dualMSB_read_sig
);

