// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Fri Sep 09 14:54:11 2011

sin400k sin400k_inst
(
	.phi_inc_i(phi_inc_i_sig) ,	// input [31:0] phi_inc_i_sig
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.clken(clken_sig) ,	// input  clken_sig
	.fsin_o(fsin_o_sig) ,	// output [13:0] fsin_o_sig
	.out_valid(out_valid_sig) 	// output  out_valid_sig
);

