// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Fri Jun 17 12:48:53 2011

peripheral_clock_crossing_s1_arbitrator peripheral_clock_crossing_s1_arbitrator_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.cpu_data_master_address_to_slave(cpu_data_master_address_to_slave_sig) ,	// input [26:0] cpu_data_master_address_to_slave_sig
	.cpu_data_master_byteenable(cpu_data_master_byteenable_sig) ,	// input [3:0] cpu_data_master_byteenable_sig
	.cpu_data_master_latency_counter(cpu_data_master_latency_counter_sig) ,	// input [1:0] cpu_data_master_latency_counter_sig
	.cpu_data_master_read(cpu_data_master_read_sig) ,	// input  cpu_data_master_read_sig
	.cpu_data_master_write(cpu_data_master_write_sig) ,	// input  cpu_data_master_write_sig
	.cpu_data_master_writedata(cpu_data_master_writedata_sig) ,	// input [31:0] cpu_data_master_writedata_sig
	.peripheral_clock_crossing_s1_endofpacket(peripheral_clock_crossing_s1_endofpacket_sig) ,	// input  peripheral_clock_crossing_s1_endofpacket_sig
	.peripheral_clock_crossing_s1_readdata(peripheral_clock_crossing_s1_readdata_sig) ,	// input [31:0] peripheral_clock_crossing_s1_readdata_sig
	.peripheral_clock_crossing_s1_readdatavalid(peripheral_clock_crossing_s1_readdatavalid_sig) ,	// input  peripheral_clock_crossing_s1_readdatavalid_sig
	.peripheral_clock_crossing_s1_waitrequest(peripheral_clock_crossing_s1_waitrequest_sig) ,	// input  peripheral_clock_crossing_s1_waitrequest_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.cpu_data_master_granted_peripheral_clock_crossing_s1(cpu_data_master_granted_peripheral_clock_crossing_s1_sig) ,	// output  cpu_data_master_granted_peripheral_clock_crossing_s1_sig
	.cpu_data_master_qualified_request_peripheral_clock_crossing_s1(cpu_data_master_qualified_request_peripheral_clock_crossing_s1_sig) ,	// output  cpu_data_master_qualified_request_peripheral_clock_crossing_s1_sig
	.cpu_data_master_read_data_valid_peripheral_clock_crossing_s1(cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_sig) ,	// output  cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_sig
	.cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register(cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register_sig) ,	// output  cpu_data_master_read_data_valid_peripheral_clock_crossing_s1_shift_register_sig
	.cpu_data_master_requests_peripheral_clock_crossing_s1(cpu_data_master_requests_peripheral_clock_crossing_s1_sig) ,	// output  cpu_data_master_requests_peripheral_clock_crossing_s1_sig
	.d1_peripheral_clock_crossing_s1_end_xfer(d1_peripheral_clock_crossing_s1_end_xfer_sig) ,	// output  d1_peripheral_clock_crossing_s1_end_xfer_sig
	.peripheral_clock_crossing_s1_address(peripheral_clock_crossing_s1_address_sig) ,	// output [4:0] peripheral_clock_crossing_s1_address_sig
	.peripheral_clock_crossing_s1_byteenable(peripheral_clock_crossing_s1_byteenable_sig) ,	// output [3:0] peripheral_clock_crossing_s1_byteenable_sig
	.peripheral_clock_crossing_s1_endofpacket_from_sa(peripheral_clock_crossing_s1_endofpacket_from_sa_sig) ,	// output  peripheral_clock_crossing_s1_endofpacket_from_sa_sig
	.peripheral_clock_crossing_s1_nativeaddress(peripheral_clock_crossing_s1_nativeaddress_sig) ,	// output [4:0] peripheral_clock_crossing_s1_nativeaddress_sig
	.peripheral_clock_crossing_s1_read(peripheral_clock_crossing_s1_read_sig) ,	// output  peripheral_clock_crossing_s1_read_sig
	.peripheral_clock_crossing_s1_readdata_from_sa(peripheral_clock_crossing_s1_readdata_from_sa_sig) ,	// output [31:0] peripheral_clock_crossing_s1_readdata_from_sa_sig
	.peripheral_clock_crossing_s1_reset_n(peripheral_clock_crossing_s1_reset_n_sig) ,	// output  peripheral_clock_crossing_s1_reset_n_sig
	.peripheral_clock_crossing_s1_waitrequest_from_sa(peripheral_clock_crossing_s1_waitrequest_from_sa_sig) ,	// output  peripheral_clock_crossing_s1_waitrequest_from_sa_sig
	.peripheral_clock_crossing_s1_write(peripheral_clock_crossing_s1_write_sig) ,	// output  peripheral_clock_crossing_s1_write_sig
	.peripheral_clock_crossing_s1_writedata(peripheral_clock_crossing_s1_writedata_sig) 	// output [31:0] peripheral_clock_crossing_s1_writedata_sig
);

