// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Wed Jun 29 17:31:31 2011

RAM RAM_inst
(
	.data(data_sig) ,	// input [15:0] data_sig
	.rdaddress(rdaddress_sig) ,	// input [10:0] rdaddress_sig
	.rdclock(rdclock_sig) ,	// input  rdclock_sig
	.wraddress(wraddress_sig) ,	// input [10:0] wraddress_sig
	.wrclock(wrclock_sig) ,	// input  wrclock_sig
	.wren(wren_sig) ,	// input  wren_sig
	.q(q_sig) 	// output [15:0] q_sig
);

