// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 9.1 (Build Build 350 03/24/2010)
// Created on Wed May 04 17:13:31 2011

sin400k_st sin400k_st_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.clken(clken_sig) ,	// input  clken_sig
	.phi_inc_i(phi_inc_i_sig) ,	// input [apr-1:0] phi_inc_i_sig
	.fsin_o(fsin_o_sig) ,	// output [mpr-1:0] fsin_o_sig
	.out_valid(out_valid_sig) 	// output  out_valid_sig
);

defparam sin400k_st_inst.mpr = 13;
defparam sin400k_st_inst.opr = 26;
defparam sin400k_st_inst.oprp1 = 27;
defparam sin400k_st_inst.apr = 32;
defparam sin400k_st_inst.apri = 16;
defparam sin400k_st_inst.aprf = 32;
defparam sin400k_st_inst.aprp = 16;
defparam sin400k_st_inst.aprid = 21;
defparam sin400k_st_inst.dpri = 5;
defparam sin400k_st_inst.rdw = 13;
defparam sin400k_st_inst.rawc = 8;
defparam sin400k_st_inst.rnwc = 256;
defparam sin400k_st_inst.rawf = 8;
defparam sin400k_st_inst.rnwf = 256;
defparam sin400k_st_inst.Pn = 16384;
defparam sin400k_st_inst.mxnbc = 3328;
defparam sin400k_st_inst.mxnbf = 3328;
defparam sin400k_st_inst.rsfc = "sin400k_sin_c.hex";
defparam sin400k_st_inst.rsff = "sin400k_sin_f.hex";
defparam sin400k_st_inst.rcfc = "sin400k_cos_c.hex";
defparam sin400k_st_inst.rcff = "sin400k_cos_f.hex";
defparam sin400k_st_inst.nc = 1;
defparam sin400k_st_inst.log2nc = 0;
defparam sin400k_st_inst.outselinit = -1;
defparam sin400k_st_inst.paci0 = 0;
defparam sin400k_st_inst.paci1 = 0;
defparam sin400k_st_inst.paci2 = 0;
defparam sin400k_st_inst.paci3 = 0;
defparam sin400k_st_inst.paci4 = 0;
defparam sin400k_st_inst.paci5 = 0;
defparam sin400k_st_inst.paci6 = 0;
defparam sin400k_st_inst.paci7 = 0;
